//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjacency_YieldChanges
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjacency_YieldChanges()
        {
            this.Districts = new HashSet<District>();
            this.Traits = new HashSet<Trait>();
            this.Improvements = new HashSet<Improvement>();
        }
    
        public string ID { get; set; }
        public string Description { get; set; }
        public string YieldType { get; set; }
        public long YieldChange { get; set; }
        public long TilesRequired { get; set; }
        public bool OtherDistrictAdjacent { get; set; }
        public bool AdjacentSeaResource { get; set; }
        public string AdjacentTerrain { get; set; }
        public string AdjacentFeature { get; set; }
        public bool AdjacentRiver { get; set; }
        public bool AdjacentWonder { get; set; }
        public bool AdjacentNaturalWonder { get; set; }
        public string AdjacentImprovement { get; set; }
        public string AdjacentDistrict { get; set; }
        public string PrereqCivic { get; set; }
        public string PrereqTech { get; set; }
        public string ObsoleteCivic { get; set; }
        public string ObsoleteTech { get; set; }
        public bool AdjacentResource { get; set; }
    
        public virtual Technology Technology { get; set; }
        public virtual Civic Civic { get; set; }
        public virtual Technology Technology1 { get; set; }
        public virtual Civic Civic1 { get; set; }
        public virtual District District { get; set; }
        public virtual Improvement Improvement { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Terrain Terrain { get; set; }
        public virtual Yield Yield { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> Districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trait> Traits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Improvement> Improvements { get; set; }
    }
}
