//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class AiBuildSpecialization
    {
        public string SpecializationType { get; set; }
        public string BuildingYield { get; set; }
        public bool IncludePopulation { get; set; }
        public bool IncludeDefense { get; set; }
        public bool IncludeMilitaryUnits { get; set; }
        public bool IncludeTradeUnits { get; set; }
        public string PrioritizationYield { get; set; }
        public long PriorityOffset { get; set; }
    
        public virtual Yield Yield { get; set; }
        public virtual Yield Yield1 { get; set; }
    }
}
