//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class AiOperationTeam
    {
        public string TeamName { get; set; }
        public string OperationName { get; set; }
        public long MinUnits { get; set; }
        public long MaxUnits { get; set; }
        public double InitialStrengthAdvantage { get; set; }
        public double OngoingStrengthAdvantage { get; set; }
        public bool SafeRallyPoint { get; set; }
    
        public virtual AiOperationDef AiOperationDef { get; set; }
        public virtual AiTeam AiTeam { get; set; }
    }
}
