//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class AiOperationDef
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AiOperationDef()
        {
            this.AiOperationTeams = new HashSet<AiOperationTeam>();
            this.AllowedOperations = new HashSet<AllowedOperation>();
            this.BoostHandlers = new HashSet<BoostHandler>();
        }
    
        public string OperationName { get; set; }
        public string TargetType { get; set; }
        public long TargetParameter { get; set; }
        public string BehaviorTree { get; set; }
        public long Priority { get; set; }
        public long MaxTargetDistInRegion { get; set; }
        public long MaxTargetDistInArea { get; set; }
        public long MaxTargetDistInWorld { get; set; }
        public long MaxTargetStrength { get; set; }
        public long MaxTargetDefense { get; set; }
        public double MinOddsOfSuccess { get; set; }
        public bool SelfStart { get; set; }
        public bool MustBeAtWar { get; set; }
        public bool MustHaveNukes { get; set; }
        public string OperationType { get; set; }
        public bool AllowTargetUpdate { get; set; }
    
        public virtual AiOperationType AiOperationType { get; set; }
        public virtual TargetType TargetType1 { get; set; }
        public virtual BehaviorTree BehaviorTree1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AiOperationTeam> AiOperationTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllowedOperation> AllowedOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoostHandler> BoostHandlers { get; set; }
    }
}
