//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class AiOperationLimit
    {
        public string ListType { get; set; }
        public string OperationType { get; set; }
        public Nullable<long> BaseValue { get; set; }
        public Nullable<long> DeltaValue { get; set; }
    
        public virtual AiOperationType AiOperationType { get; set; }
        public virtual AiOperationList AiOperationList { get; set; }
    }
}
