//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowedOperation
    {
        public string ListType { get; set; }
        public string OperationDef { get; set; }
        public bool RemoveRef { get; set; }
    
        public virtual AiOperationDef AiOperationDef { get; set; }
        public virtual AiOperationList AiOperationList { get; set; }
    }
}
