//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarbarianTribeName
    {
        public string TribeNameType { get; set; }
        public string TribeType { get; set; }
        public Nullable<long> NumMilitary { get; set; }
        public Nullable<long> NumScouts { get; set; }
        public Nullable<long> PercentRangedUnits { get; set; }
        public Nullable<long> TurnsToWarriorSpawn { get; set; }
        public string TribeDisplayName { get; set; }
        public string ScoutingBehaviorTree { get; set; }
        public string RaidingBehaviorTree { get; set; }
        public Nullable<long> RaidingBoldness { get; set; }
    
        public virtual BarbarianTribe BarbarianTribe { get; set; }
    }
}
