//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarbarianTribe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarbarianTribe()
        {
            this.BarbarianTribeNames = new HashSet<BarbarianTribeName>();
        }
    
        public string TribeType { get; set; }
        public bool IsCoastal { get; set; }
        public string RequiredResource { get; set; }
        public long ResourceRange { get; set; }
        public long PercentRangedUnits { get; set; }
        public long TurnsToWarriorSpawn { get; set; }
        public string ScoutTag { get; set; }
        public string MeleeTag { get; set; }
        public string RangedTag { get; set; }
        public string SiegeTag { get; set; }
        public string DefenderTag { get; set; }
        public string SupportTag { get; set; }
        public string ScoutingBehaviorTree { get; set; }
        public string RaidingBehaviorTree { get; set; }
        public long RaidingBoldness { get; set; }
        public string CityAttackOperation { get; set; }
        public long CityAttackBoldness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarbarianTribeName> BarbarianTribeNames { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
