//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorTreeNode
    {
        public string TreeName { get; set; }
        public long NodeId { get; set; }
        public long JumpTo { get; set; }
        public string NodeType { get; set; }
        public long PrimaryKey { get; set; }
    
        public virtual NodeDefinition NodeDefinition { get; set; }
        public virtual BehaviorTree BehaviorTree { get; set; }
    }
}
