//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoostHandler
    {
        public string HandlerId { get; set; }
        public string TechBoostType { get; set; }
        public string BehaviorTree { get; set; }
        public string OperationName { get; set; }
        public string LuaScript { get; set; }
        public string UniquenessTag { get; set; }
        public string WinnowFunction { get; set; }
    
        public virtual AiOperationDef AiOperationDef { get; set; }
        public virtual BehaviorTree BehaviorTree1 { get; set; }
        public virtual BoostName BoostName { get; set; }
    }
}
