//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boost
    {
        public long BoostID { get; set; }
        public string TechnologyType { get; set; }
        public string CivicType { get; set; }
        public long Boost1 { get; set; }
        public long TriggerId { get; set; }
        public string TriggerDescription { get; set; }
        public string TriggerLongDescription { get; set; }
        public string Unit1Type { get; set; }
        public string BoostClass { get; set; }
        public string Unit2Type { get; set; }
        public string BuildingType { get; set; }
        public string ImprovementType { get; set; }
        public string BoostingTechType { get; set; }
        public string ResourceType { get; set; }
        public long NumItems { get; set; }
        public string DistrictType { get; set; }
        public bool RequiresResource { get; set; }
        public string RequirementSetId { get; set; }
        public string GovernmentSlotType { get; set; }
        public string BoostingCivicType { get; set; }
    
        public virtual BoostName BoostName { get; set; }
        public virtual GovernmentSlot GovernmentSlot { get; set; }
        public virtual Civic Civic { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual Civic Civic1 { get; set; }
        public virtual Technology Technology1 { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual District District { get; set; }
        public virtual Improvement Improvement { get; set; }
        public virtual Building Building { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
