//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameplayEntities : DbContext
    {
        public GameplayEntities()
            : base("name=GameplayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjacency_YieldChanges> Adjacency_YieldChanges { get; set; }
        public virtual DbSet<Agenda> Agendas { get; set; }
        public virtual DbSet<AiBuildSpecialization> AiBuildSpecializations { get; set; }
        public virtual DbSet<AiEvent> AiEvents { get; set; }
        public virtual DbSet<AiFavoredItem> AiFavoredItems { get; set; }
        public virtual DbSet<AiList> AiLists { get; set; }
        public virtual DbSet<AiListType> AiListTypes { get; set; }
        public virtual DbSet<AiOperationDef> AiOperationDefs { get; set; }
        public virtual DbSet<AiOperationLimit> AiOperationLimits { get; set; }
        public virtual DbSet<AiOperationList> AiOperationLists { get; set; }
        public virtual DbSet<AiOperationTeam> AiOperationTeams { get; set; }
        public virtual DbSet<AiOperationType> AiOperationTypes { get; set; }
        public virtual DbSet<AiTeam> AiTeams { get; set; }
        public virtual DbSet<AllowedMove> AllowedMoves { get; set; }
        public virtual DbSet<AllowedOperation> AllowedOperations { get; set; }
        public virtual DbSet<AppealHousingChanx> AppealHousingChanges { get; set; }
        public virtual DbSet<BarbarianTribeName> BarbarianTribeNames { get; set; }
        public virtual DbSet<BarbarianTribe> BarbarianTribes { get; set; }
        public virtual DbSet<BehaviorTreeNode> BehaviorTreeNodes { get; set; }
        public virtual DbSet<BehaviorTree> BehaviorTrees { get; set; }
        public virtual DbSet<BeliefClass> BeliefClasses { get; set; }
        public virtual DbSet<BeliefModifier> BeliefModifiers { get; set; }
        public virtual DbSet<Belief> Beliefs { get; set; }
        public virtual DbSet<BonusMinorStartingUnit> BonusMinorStartingUnits { get; set; }
        public virtual DbSet<BoostHandler> BoostHandlers { get; set; }
        public virtual DbSet<BoostName> BoostNames { get; set; }
        public virtual DbSet<Boost> Boosts { get; set; }
        public virtual DbSet<Building_GreatPersonPoints> Building_GreatPersonPoints { get; set; }
        public virtual DbSet<Building_GreatWorks> Building_GreatWorks { get; set; }
        public virtual DbSet<Building_YieldChanges> Building_YieldChanges { get; set; }
        public virtual DbSet<Building_YieldDistrictCopies> Building_YieldDistrictCopies { get; set; }
        public virtual DbSet<BuildingModifier> BuildingModifiers { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<CityEvent> CityEvents { get; set; }
        public virtual DbSet<CityName> CityNames { get; set; }
        public virtual DbSet<CivicModifier> CivicModifiers { get; set; }
        public virtual DbSet<CivicQuote> CivicQuotes { get; set; }
        public virtual DbSet<Civic> Civics { get; set; }
        public virtual DbSet<CivilizationCitizenName> CivilizationCitizenNames { get; set; }
        public virtual DbSet<CivilizationInfo> CivilizationInfoes { get; set; }
        public virtual DbSet<CivilizationLeader> CivilizationLeaders { get; set; }
        public virtual DbSet<CivilizationLevel> CivilizationLevels { get; set; }
        public virtual DbSet<Civilization> Civilizations { get; set; }
        public virtual DbSet<CivilopediaPageGroupQuery> CivilopediaPageGroupQueries { get; set; }
        public virtual DbSet<CivilopediaPageGroup> CivilopediaPageGroups { get; set; }
        public virtual DbSet<CivilopediaPageLayoutChapter> CivilopediaPageLayoutChapters { get; set; }
        public virtual DbSet<CivilopediaPageLayout> CivilopediaPageLayouts { get; set; }
        public virtual DbSet<CivilopediaPageQuery> CivilopediaPageQueries { get; set; }
        public virtual DbSet<CivilopediaPage> CivilopediaPages { get; set; }
        public virtual DbSet<CivilopediaSection> CivilopediaSections { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<DataType> DataTypes { get; set; }
        public virtual DbSet<DealItem> DealItems { get; set; }
        public virtual DbSet<Defeat> Defeats { get; set; }
        public virtual DbSet<Difficulty> Difficulties { get; set; }
        public virtual DbSet<District_CitizenGreatPersonPoints> District_CitizenGreatPersonPoints { get; set; }
        public virtual DbSet<District_CitizenYieldChanges> District_CitizenYieldChanges { get; set; }
        public virtual DbSet<District_GreatPersonPoints> District_GreatPersonPoints { get; set; }
        public virtual DbSet<District_TradeRouteYields> District_TradeRouteYields { get; set; }
        public virtual DbSet<DistrictModifier> DistrictModifiers { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<DynamicModifier> DynamicModifiers { get; set; }
        public virtual DbSet<Era> Eras { get; set; }
        public virtual DbSet<FavoredReligion> FavoredReligions { get; set; }
        public virtual DbSet<Feature_AdjacentYields> Feature_AdjacentYields { get; set; }
        public virtual DbSet<Feature_Removes> Feature_Removes { get; set; }
        public virtual DbSet<Feature_YieldChanges> Feature_YieldChanges { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Flavor> Flavors { get; set; }
        public virtual DbSet<GameModifier> GameModifiers { get; set; }
        public virtual DbSet<GameSpeed_Turns> GameSpeed_Turns { get; set; }
        public virtual DbSet<GameSpeed> GameSpeeds { get; set; }
        public virtual DbSet<GlobalParameter> GlobalParameters { get; set; }
        public virtual DbSet<GoodyHut> GoodyHuts { get; set; }
        public virtual DbSet<GoodyHutSubType> GoodyHutSubTypes { get; set; }
        public virtual DbSet<Gossip> Gossips { get; set; }
        public virtual DbSet<Government_SlotCounts> Government_SlotCounts { get; set; }
        public virtual DbSet<GovernmentBonusName> GovernmentBonusNames { get; set; }
        public virtual DbSet<GovernmentModifier> GovernmentModifiers { get; set; }
        public virtual DbSet<Government> Governments { get; set; }
        public virtual DbSet<GovernmentSlot> GovernmentSlots { get; set; }
        public virtual DbSet<GreatPersonClass> GreatPersonClasses { get; set; }
        public virtual DbSet<GreatPersonIndividualActionModifier> GreatPersonIndividualActionModifiers { get; set; }
        public virtual DbSet<GreatPersonIndividualBirthModifier> GreatPersonIndividualBirthModifiers { get; set; }
        public virtual DbSet<GreatPersonIndividual> GreatPersonIndividuals { get; set; }
        public virtual DbSet<GreatWork_YieldChanges> GreatWork_YieldChanges { get; set; }
        public virtual DbSet<GreatWorkObjectType> GreatWorkObjectTypes { get; set; }
        public virtual DbSet<GreatWork> GreatWorks { get; set; }
        public virtual DbSet<GreatWorkSlotType> GreatWorkSlotTypes { get; set; }
        public virtual DbSet<Happiness> Happinesses { get; set; }
        public virtual DbSet<HistoricRanking> HistoricRankings { get; set; }
        public virtual DbSet<Improvement_BonusYieldChanges> Improvement_BonusYieldChanges { get; set; }
        public virtual DbSet<Improvement_Tourism> Improvement_Tourism { get; set; }
        public virtual DbSet<Improvement_ValidResources> Improvement_ValidResources { get; set; }
        public virtual DbSet<Improvement_ValidTerrains> Improvement_ValidTerrains { get; set; }
        public virtual DbSet<Improvement_YieldChanges> Improvement_YieldChanges { get; set; }
        public virtual DbSet<ImprovementModifier> ImprovementModifiers { get; set; }
        public virtual DbSet<Improvement> Improvements { get; set; }
        public virtual DbSet<InterfaceMode> InterfaceModes { get; set; }
        public virtual DbSet<Kind> Kinds { get; set; }
        public virtual DbSet<LeaderAnimation> LeaderAnimations { get; set; }
        public virtual DbSet<LeaderInfo> LeaderInfoes { get; set; }
        public virtual DbSet<LeaderQuote> LeaderQuotes { get; set; }
        public virtual DbSet<Leader> Leaders { get; set; }
        public virtual DbSet<MajorStartingUnit> MajorStartingUnits { get; set; }
        public virtual DbSet<Map_GreatPersonClasses> Map_GreatPersonClasses { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<ModifierArgument> ModifierArguments { get; set; }
        public virtual DbSet<Modifier> Modifiers { get; set; }
        public virtual DbSet<ModifierString> ModifierStrings { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<NavigationProperty> NavigationProperties { get; set; }
        public virtual DbSet<NodeDataDefinition> NodeDataDefinitions { get; set; }
        public virtual DbSet<NodeDefinition> NodeDefinitions { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<ObsoletePolicy> ObsoletePolicies { get; set; }
        public virtual DbSet<OpTeamRequirement> OpTeamRequirements { get; set; }
        public virtual DbSet<PlayerColor> PlayerColors { get; set; }
        public virtual DbSet<PlotEvalCondition> PlotEvalConditions { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PolicyModifier> PolicyModifiers { get; set; }
        public virtual DbSet<Project_GreatPersonPoints> Project_GreatPersonPoints { get; set; }
        public virtual DbSet<Project_YieldConversions> Project_YieldConversions { get; set; }
        public virtual DbSet<ProjectCompletionModifier> ProjectCompletionModifiers { get; set; }
        public virtual DbSet<ProjectPrereq> ProjectPrereqs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<PseudoYield> PseudoYields { get; set; }
        public virtual DbSet<Quest> Quests { get; set; }
        public virtual DbSet<RandomAgenda> RandomAgendas { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<RequirementArgument> RequirementArguments { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<RequirementSet> RequirementSets { get; set; }
        public virtual DbSet<RequirementString> RequirementStrings { get; set; }
        public virtual DbSet<Resource_Distribution> Resource_Distribution { get; set; }
        public virtual DbSet<Resource_Harvests> Resource_Harvests { get; set; }
        public virtual DbSet<Resource_TradeRouteYields> Resource_TradeRouteYields { get; set; }
        public virtual DbSet<Resource_YieldChanges> Resource_YieldChanges { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<SavingType> SavingTypes { get; set; }
        public virtual DbSet<ScoringCategory> ScoringCategories { get; set; }
        public virtual DbSet<ScoringLineItem> ScoringLineItems { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SettlementPreference> SettlementPreferences { get; set; }
        public virtual DbSet<ShapeDefinition> ShapeDefinitions { get; set; }
        public virtual DbSet<StartBiasFeature> StartBiasFeatures { get; set; }
        public virtual DbSet<StartBiasResource> StartBiasResources { get; set; }
        public virtual DbSet<StartBiasRiver> StartBiasRivers { get; set; }
        public virtual DbSet<StartBiasTerrain> StartBiasTerrains { get; set; }
        public virtual DbSet<StartEra> StartEras { get; set; }
        public virtual DbSet<StartingBuilding> StartingBuildings { get; set; }
        public virtual DbSet<StartingGovernment> StartingGovernments { get; set; }
        public virtual DbSet<Strategy> Strategies { get; set; }
        public virtual DbSet<Strategy_YieldPriorities> Strategy_YieldPriorities { get; set; }
        public virtual DbSet<StrategyCondition> StrategyConditions { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TargetType> TargetTypes { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<TechnologyModifier> TechnologyModifiers { get; set; }
        public virtual DbSet<TechnologyQuote> TechnologyQuotes { get; set; }
        public virtual DbSet<Terrain_YieldChanges> Terrain_YieldChanges { get; set; }
        public virtual DbSet<Terrain> Terrains { get; set; }
        public virtual DbSet<TraitModifier> TraitModifiers { get; set; }
        public virtual DbSet<Trait> Traits { get; set; }
        public virtual DbSet<TreeData> TreeDatas { get; set; }
        public virtual DbSet<TriggeredBehaviorTree> TriggeredBehaviorTrees { get; set; }
        public virtual DbSet<TurnPhas> TurnPhases { get; set; }
        public virtual DbSet<TurnSegment> TurnSegments { get; set; }
        public virtual DbSet<TurnTimer> TurnTimers { get; set; }
        public virtual DbSet<TypeProperty> TypeProperties { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Unit_BuildingPrereqs> Unit_BuildingPrereqs { get; set; }
        public virtual DbSet<Unit_RebellionTags> Unit_RebellionTags { get; set; }
        public virtual DbSet<UnitAbility> UnitAbilities { get; set; }
        public virtual DbSet<UnitAiType> UnitAiTypes { get; set; }
        public virtual DbSet<UnitCommand> UnitCommands { get; set; }
        public virtual DbSet<UnitFormationClass> UnitFormationClasses { get; set; }
        public virtual DbSet<UnitName> UnitNames { get; set; }
        public virtual DbSet<UnitOperation> UnitOperations { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Victory> Victories { get; set; }
        public virtual DbSet<Visibility> Visibilities { get; set; }
        public virtual DbSet<Vocabulary> Vocabularies { get; set; }
        public virtual DbSet<WMD> WMDs { get; set; }
        public virtual DbSet<Yield> Yields { get; set; }
    }
}
