//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilizationLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CivilizationLevel()
        {
            this.Civilizations = new HashSet<Civilization>();
        }
    
        public string CivilizationLevelType { get; set; }
        public bool CanFoundCities { get; set; }
        public bool CanAnnexTilesWithCulture { get; set; }
        public bool CanAnnexTilesWithGold { get; set; }
        public bool CanAnnexTilesWithReceivedInfluence { get; set; }
        public bool CanEarnGreatPeople { get; set; }
        public bool CanGiveInfluence { get; set; }
        public bool CanReceiveInfluence { get; set; }
        public long StartingTilesForCity { get; set; }
        public bool CanBuildWonders { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Civilization> Civilizations { get; set; }
    }
}
