//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilopediaPageGroupQuery
    {
        public long RowId { get; set; }
        public string SectionId { get; set; }
        public string SQL { get; set; }
        public string PageGroupIdColumn { get; set; }
        public string NameColumn { get; set; }
        public string TooltipColumn { get; set; }
        public string VisibleIfEmptyColumn { get; set; }
        public string SortIndexColumn { get; set; }
        public long SortIndex { get; set; }
    }
}
