//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilopediaPageGroup
    {
        public string SectionId { get; set; }
        public string PageGroupId { get; set; }
        public string Name { get; set; }
        public string Tooltip { get; set; }
        public bool VisibleIfEmpty { get; set; }
        public long SortIndex { get; set; }
    }
}
