//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Civilization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Civilization()
        {
            this.CityNames = new HashSet<CityName>();
            this.CivilizationCitizenNames = new HashSet<CivilizationCitizenName>();
            this.CivilizationInfoes = new HashSet<CivilizationInfo>();
            this.CivilizationLeaders = new HashSet<CivilizationLeader>();
            this.FavoredReligions = new HashSet<FavoredReligion>();
            this.StartBiasFeatures = new HashSet<StartBiasFeature>();
            this.StartBiasResources = new HashSet<StartBiasResource>();
            this.StartBiasTerrains = new HashSet<StartBiasTerrain>();
            this.Traits = new HashSet<Trait>();
        }
    
        public string CivilizationType { get; set; }
        public string Description { get; set; }
        public string Adjective { get; set; }
        public long RandomCityNameDepth { get; set; }
        public string StartingCivilizationLevelType { get; set; }
        public string Ethnicity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CityName> CityNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CivilizationCitizenName> CivilizationCitizenNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CivilizationInfo> CivilizationInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CivilizationLeader> CivilizationLeaders { get; set; }
        public virtual CivilizationLevel CivilizationLevel { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoredReligion> FavoredReligions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartBiasFeature> StartBiasFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartBiasResource> StartBiasResources { get; set; }
        public virtual StartBiasRiver StartBiasRiver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartBiasTerrain> StartBiasTerrains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trait> Traits { get; set; }
    }
}
