//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defeat
    {
        public string DefeatType { get; set; }
        public string Name { get; set; }
        public string Blurb { get; set; }
        public string RequirementSetId { get; set; }
        public bool EnabledByDefault { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
