//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicModifier
    {
        public string ModifierType { get; set; }
        public string CollectionType { get; set; }
        public string EffectType { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
        public virtual Type Type2 { get; set; }
    }
}
