//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature_Removes
    {
        public string FeatureType { get; set; }
        public string YieldType { get; set; }
        public long Yield { get; set; }
    
        public virtual Yield Yield1 { get; set; }
        public virtual Feature Feature { get; set; }
    }
}
