//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSpeed_Turns
    {
        public string GameSpeedType { get; set; }
        public long MonthIncrement { get; set; }
        public long TurnsPerIncrement { get; set; }
    
        public virtual GameSpeed GameSpeed { get; set; }
    }
}
