//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSpeed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameSpeed()
        {
            this.GameSpeed_Turns = new HashSet<GameSpeed_Turns>();
        }
    
        public string GameSpeedType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long CostMultiplier { get; set; }
        public long CivicUnlockMaxCost { get; set; }
        public long CivicUnlockPerTurnDrop { get; set; }
        public long CivicUnlockMinCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameSpeed_Turns> GameSpeed_Turns { get; set; }
    }
}
