//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodyHut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodyHut()
        {
            this.GoodyHutSubTypes = new HashSet<GoodyHutSubType>();
        }
    
        public string GoodyHutType { get; set; }
        public string ImprovementType { get; set; }
        public long Weight { get; set; }
    
        public virtual Improvement Improvement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodyHutSubType> GoodyHutSubTypes { get; set; }
    }
}
