//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodyHutSubType
    {
        public string GoodyHut { get; set; }
        public string SubTypeGoodyHut { get; set; }
        public string Description { get; set; }
        public long Weight { get; set; }
        public string ModifierID { get; set; }
        public bool UpgradeUnit { get; set; }
        public long Turn { get; set; }
        public bool Experience { get; set; }
        public long Heal { get; set; }
        public bool Relic { get; set; }
        public bool Trader { get; set; }
        public bool MinOneCity { get; set; }
        public bool RequiresUnit { get; set; }
    
        public virtual GoodyHut GoodyHut1 { get; set; }
    }
}
