//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gossip
    {
        public string GossipType { get; set; }
        public long VisibilityLevel { get; set; }
        public string Description { get; set; }
        public string Message { get; set; }
        public bool Filter { get; set; }
    }
}
