//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Government_SlotCounts
    {
        public string GovernmentType { get; set; }
        public string GovernmentSlotType { get; set; }
        public long NumSlots { get; set; }
    
        public virtual GovernmentSlot GovernmentSlot { get; set; }
        public virtual Government Government { get; set; }
    }
}
