//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreatPersonIndividual
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreatPersonIndividual()
        {
            this.GreatPersonIndividualActionModifiers = new HashSet<GreatPersonIndividualActionModifier>();
            this.GreatPersonIndividualBirthModifiers = new HashSet<GreatPersonIndividualBirthModifier>();
            this.GreatWorks = new HashSet<GreatWork>();
        }
    
        public string GreatPersonIndividualType { get; set; }
        public string Name { get; set; }
        public string GreatPersonClassType { get; set; }
        public string EraType { get; set; }
        public long ActionCharges { get; set; }
        public bool ActionRequiresOwnedTile { get; set; }
        public bool ActionRequiresUnownedTile { get; set; }
        public bool ActionRequiresAdjacentMountain { get; set; }
        public bool ActionRequiresAdjacentOwnedTile { get; set; }
        public bool ActionRequiresAdjacentBarbarianUnit { get; set; }
        public bool ActionRequiresOnOrAdjacentNaturalWonder { get; set; }
        public string ActionRequiresOnOrAdjacentFeatureType { get; set; }
        public bool ActionRequiresIncompleteWonder { get; set; }
        public bool ActionRequiresIncompleteSpaceRaceProject { get; set; }
        public bool ActionRequiresVisibleLuxury { get; set; }
        public bool ActionRequiresNoMilitaryUnit { get; set; }
        public bool ActionRequiresPlayerRelicSlot { get; set; }
        public string ActionRequiresMilitaryUnitDomain { get; set; }
        public string ActionRequiresUnitMilitaryFormation { get; set; }
        public string ActionRequiresCityGreatWorkObjectType { get; set; }
        public string ActionRequiresCompletedDistrictType { get; set; }
        public string ActionRequiresMissingBuildingType { get; set; }
        public Nullable<long> ActionRequiresGoldCost { get; set; }
        public string ActionNameTextOverride { get; set; }
        public string ActionEffectTextOverride { get; set; }
        public bool ActionEffectTileHighlighting { get; set; }
        public string BirthNameTextOverride { get; set; }
        public string BirthEffectTextOverride { get; set; }
        public Nullable<long> AreaHighlightRadius { get; set; }
        public string Gender { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual District District { get; set; }
        public virtual Era Era { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual GreatPersonClass GreatPersonClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatPersonIndividualActionModifier> GreatPersonIndividualActionModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatPersonIndividualBirthModifier> GreatPersonIndividualBirthModifiers { get; set; }
        public virtual GreatWorkObjectType GreatWorkObjectType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatWork> GreatWorks { get; set; }
    }
}
