//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreatWorkObjectType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreatWorkObjectType()
        {
            this.GreatPersonIndividuals = new HashSet<GreatPersonIndividual>();
            this.GreatWorks = new HashSet<GreatWork>();
            this.GreatWorkSlotTypes = new HashSet<GreatWorkSlotType>();
        }
    
        public string GreatWorkObjectType1 { get; set; }
        public long Value { get; set; }
        public string PseudoYieldType { get; set; }
        public string Name { get; set; }
        public string IconString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatPersonIndividual> GreatPersonIndividuals { get; set; }
        public virtual PseudoYield PseudoYield { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatWork> GreatWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatWorkSlotType> GreatWorkSlotTypes { get; set; }
    }
}
