//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreatWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreatWork()
        {
            this.GreatWork_YieldChanges = new HashSet<GreatWork_YieldChanges>();
        }
    
        public string GreatWorkType { get; set; }
        public string GreatWorkObjectType { get; set; }
        public string GreatPersonIndividualType { get; set; }
        public string Name { get; set; }
        public string Audio { get; set; }
        public string Image { get; set; }
        public string Quote { get; set; }
        public long Tourism { get; set; }
        public string EraType { get; set; }
    
        public virtual Era Era { get; set; }
        public virtual GreatPersonIndividual GreatPersonIndividual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatWork_YieldChanges> GreatWork_YieldChanges { get; set; }
        public virtual GreatWorkObjectType GreatWorkObjectType1 { get; set; }
    }
}
