//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreatPersonClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GreatPersonClass()
        {
            this.Building_GreatPersonPoints = new HashSet<Building_GreatPersonPoints>();
            this.District_CitizenGreatPersonPoints = new HashSet<District_CitizenGreatPersonPoints>();
            this.District_GreatPersonPoints = new HashSet<District_GreatPersonPoints>();
            this.GreatPersonIndividuals = new HashSet<GreatPersonIndividual>();
            this.Map_GreatPersonClasses = new HashSet<Map_GreatPersonClasses>();
            this.ObsoletePolicies = new HashSet<ObsoletePolicy>();
            this.Project_GreatPersonPoints = new HashSet<Project_GreatPersonPoints>();
            this.Traits = new HashSet<Trait>();
        }
    
        public string GreatPersonClassType { get; set; }
        public string Name { get; set; }
        public string UnitType { get; set; }
        public string DistrictType { get; set; }
        public Nullable<long> MaxPlayerInstances { get; set; }
        public string PseudoYieldType { get; set; }
        public string IconString { get; set; }
        public string ActionIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Building_GreatPersonPoints> Building_GreatPersonPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District_CitizenGreatPersonPoints> District_CitizenGreatPersonPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District_GreatPersonPoints> District_GreatPersonPoints { get; set; }
        public virtual District District { get; set; }
        public virtual PseudoYield PseudoYield { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreatPersonIndividual> GreatPersonIndividuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map_GreatPersonClasses> Map_GreatPersonClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObsoletePolicy> ObsoletePolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_GreatPersonPoints> Project_GreatPersonPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trait> Traits { get; set; }
    }
}
