//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Happiness
    {
        public string HappinessType { get; set; }
        public string Name { get; set; }
        public Nullable<long> MinimumAmenityScore { get; set; }
        public Nullable<long> MaximumAmenityScore { get; set; }
        public Nullable<double> GrowthModifier { get; set; }
        public Nullable<double> NonFoodYieldModifier { get; set; }
        public long RebellionPoints { get; set; }
    }
}
