//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Improvement_ValidTerrains
    {
        public string ImprovementType { get; set; }
        public string TerrainType { get; set; }
        public string PrereqTech { get; set; }
        public string PrereqCivic { get; set; }
    
        public virtual Civic Civic { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual Terrain Terrain { get; set; }
        public virtual Improvement Improvement { get; set; }
    }
}
