//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceMode
    {
        public string ModeType { get; set; }
        public string Description { get; set; }
        public string Help { get; set; }
        public string DisabledHelp { get; set; }
        public string Icon { get; set; }
        public bool VisibleInUI { get; set; }
        public string CursorType { get; set; }
    }
}
