//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderInfo
    {
        public string LeaderType { get; set; }
        public string Header { get; set; }
        public string Caption { get; set; }
        public long SortIndex { get; set; }
    
        public virtual Leader Leader { get; set; }
    }
}
