//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Map()
        {
            this.Map_GreatPersonClasses = new HashSet<Map_GreatPersonClasses>();
        }
    
        public string MapSizeType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long DefaultPlayers { get; set; }
        public long FogTilesPerBarbarianCamp { get; set; }
        public long NumNaturalWonders { get; set; }
        public long UnitNameModifier { get; set; }
        public long TargetNumCities { get; set; }
        public long GridWidth { get; set; }
        public long GridHeight { get; set; }
        public long TerrainGrainChange { get; set; }
        public long FeatureGrainChange { get; set; }
        public long ResearchPercent { get; set; }
        public long NumCitiesUnhealthPercent { get; set; }
        public long NumCitiesPolicyCostMod { get; set; }
        public long NumCitiesTechCostMod { get; set; }
        public long EstimatedNumCities { get; set; }
        public long PlateValue { get; set; }
        public long Continents { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map_GreatPersonClasses> Map_GreatPersonClasses { get; set; }
    }
}
