//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modifier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modifier()
        {
            this.ModifierArguments = new HashSet<ModifierArgument>();
            this.ModifierStrings = new HashSet<ModifierString>();
            this.UnitAbilities = new HashSet<UnitAbility>();
        }
    
        public string ModifierId { get; set; }
        public string ModifierType { get; set; }
        public bool RunOnce { get; set; }
        public bool Permanent { get; set; }
        public string OwnerRequirementSetId { get; set; }
        public string SubjectRequirementSetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModifierArgument> ModifierArguments { get; set; }
        public virtual RequirementSet RequirementSet { get; set; }
        public virtual RequirementSet RequirementSet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModifierString> ModifierStrings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitAbility> UnitAbilities { get; set; }
    }
}
