//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavigationProperty
    {
        public string BaseTable { get; set; }
        public string PropertyName { get; set; }
        public string TargetTable { get; set; }
        public Nullable<long> IsCollection { get; set; }
        public string Query { get; set; }
    }
}
