//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeDataDefinition
    {
        public string DataName { get; set; }
        public long DefnId { get; set; }
        public string DataType { get; set; }
        public string NodeType { get; set; }
        public bool Required { get; set; }
        public bool RequiredGroup { get; set; }
        public bool Output { get; set; }
        public bool Modified { get; set; }
        public bool UserData { get; set; }
        public bool Automatic { get; set; }
        public bool Tagged { get; set; }
        public string EnumList { get; set; }
        public long UniqueId { get; set; }
    
        public virtual NodeDefinition NodeDefinition { get; set; }
    }
}
