//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NodeDefinition()
        {
            this.BehaviorTreeNodes = new HashSet<BehaviorTreeNode>();
            this.NodeDataDefinitions = new HashSet<NodeDataDefinition>();
        }
    
        public string NodeType { get; set; }
        public long NodeId { get; set; }
        public long ShapeId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviorTreeNode> BehaviorTreeNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodeDataDefinition> NodeDataDefinitions { get; set; }
        public virtual ShapeDefinition ShapeDefinition { get; set; }
    }
}
