//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string NotificationType { get; set; }
        public string Message { get; set; }
        public string Summary { get; set; }
        public string SeverityType { get; set; }
        public bool ExpiresEndOfTurn { get; set; }
        public bool ExpiresEndOfNextTurn { get; set; }
        public string SubType { get; set; }
        public bool AutoNotify { get; set; }
        public string GroupType { get; set; }
        public string Icon { get; set; }
    }
}
