//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpTeamRequirement
    {
        public string TeamName { get; set; }
        public string AiType { get; set; }
        public Nullable<long> MinNumber { get; set; }
        public Nullable<long> MaxNumber { get; set; }
        public double MinPercentage { get; set; }
        public double MaxPercentage { get; set; }
        public bool ReconsiderWhilePreparing { get; set; }
    
        public virtual AiTeam AiTeam { get; set; }
        public virtual UnitAiType UnitAiType { get; set; }
    }
}
