//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.ObsoletePolicies = new HashSet<ObsoletePolicy>();
            this.ObsoletePolicies1 = new HashSet<ObsoletePolicy>();
            this.PolicyModifiers = new HashSet<PolicyModifier>();
        }
    
        public string PolicyType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PrereqCivic { get; set; }
        public string GovernmentSlotType { get; set; }
    
        public virtual Civic Civic { get; set; }
        public virtual GovernmentSlot GovernmentSlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObsoletePolicy> ObsoletePolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObsoletePolicy> ObsoletePolicies1 { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyModifier> PolicyModifiers { get; set; }
    }
}
