//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Project_GreatPersonPoints = new HashSet<Project_GreatPersonPoints>();
            this.Project_YieldConversions = new HashSet<Project_YieldConversions>();
            this.ProjectCompletionModifiers = new HashSet<ProjectCompletionModifier>();
            this.ProjectPrereqs = new HashSet<ProjectPrereq>();
            this.ProjectPrereqs1 = new HashSet<ProjectPrereq>();
        }
    
        public string ProjectType { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string PopupText { get; set; }
        public long Cost { get; set; }
        public string CostProgressionModel { get; set; }
        public long CostProgressionParam1 { get; set; }
        public string PrereqTech { get; set; }
        public string PrereqCivic { get; set; }
        public string PrereqDistrict { get; set; }
        public string VisualBuildingType { get; set; }
        public bool SpaceRace { get; set; }
        public bool OuterDefenseRepair { get; set; }
        public Nullable<long> MaxPlayerInstances { get; set; }
        public Nullable<long> AmenitiesWhileActive { get; set; }
        public string PrereqResource { get; set; }
        public string AdvisorType { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Civic Civic { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_GreatPersonPoints> Project_GreatPersonPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_YieldConversions> Project_YieldConversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCompletionModifier> ProjectCompletionModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPrereq> ProjectPrereqs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPrereq> ProjectPrereqs1 { get; set; }
        public virtual Type Type { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
