//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_GreatPersonPoints
    {
        public string ProjectType { get; set; }
        public string GreatPersonClassType { get; set; }
        public long Points { get; set; }
        public string PointProgressionModel { get; set; }
        public long PointProgressionParam1 { get; set; }
    
        public virtual GreatPersonClass GreatPersonClass { get; set; }
        public virtual Project Project { get; set; }
    }
}
