//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_YieldConversions
    {
        public string ProjectType { get; set; }
        public string YieldType { get; set; }
        public long PercentOfProductionRate { get; set; }
    
        public virtual Yield Yield { get; set; }
        public virtual Project Project { get; set; }
    }
}
