//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public string QuestType { get; set; }
        public string Name { get; set; }
        public string InstanceName { get; set; }
        public string Description { get; set; }
        public string InstanceDescription { get; set; }
        public string Reward { get; set; }
        public string InstanceReward { get; set; }
        public string IconString { get; set; }
    }
}
