//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_Distribution
    {
        public long Continents { get; set; }
        public long Scarce { get; set; }
        public long Average { get; set; }
        public long Plentiful { get; set; }
        public long PercentAdjusted { get; set; }
    }
}
