//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Units = new HashSet<Unit>();
        }
    
        public string RouteType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double MovementCost { get; set; }
        public bool SupportsBridges { get; set; }
        public long PlacementValue { get; set; }
        public bool PlacementRequiresRoutePresent { get; set; }
        public bool PlacementRequiresOwnedTile { get; set; }
        public string PrereqEra { get; set; }
    
        public virtual Era Era { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unit> Units { get; set; }
    }
}
