//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoringLineItem
    {
        public string LineItemType { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public double Multiplier { get; set; }
        public bool ScaleByCost { get; set; }
        public bool Civics { get; set; }
        public bool Cities { get; set; }
        public bool Districts { get; set; }
        public bool Population { get; set; }
        public bool GreatPeople { get; set; }
        public bool Techs { get; set; }
        public bool Wonders { get; set; }
        public bool Religion { get; set; }
        public bool Pillage { get; set; }
        public bool Trade { get; set; }
        public long TieBreakerPriority { get; set; }
        public bool ScoringScenario1 { get; set; }
        public bool ScoringScenario2 { get; set; }
        public bool ScoringScenario3 { get; set; }
    
        public virtual ScoringCategory ScoringCategory { get; set; }
    }
}
