//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartingGovernment
    {
        public string Government { get; set; }
        public string Era { get; set; }
        public bool Change { get; set; }
    
        public virtual Era Era1 { get; set; }
        public virtual Government Government1 { get; set; }
    }
}
