//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartEra
    {
        public string EraType { get; set; }
        public long Gold { get; set; }
        public long Faith { get; set; }
        public bool FirstTurnCivicChange { get; set; }
        public long StartingPopulationCapital { get; set; }
        public long StartingPopulationOtherCities { get; set; }
        public long GrowthRate { get; set; }
        public long ProductionRate { get; set; }
        public long DistrictProductionRate { get; set; }
        public long StartingMeleeStrengthMajor { get; set; }
        public long StartingMeleeStrengthMinor { get; set; }
        public bool ObsoleteReligion { get; set; }
        public long Tiles { get; set; }
        public long Year { get; set; }
        public bool IgnoreGoodyHutTurn { get; set; }
        public long StartingRangedStrengthMajor { get; set; }
        public long StartingRangedStrengthMinor { get; set; }
        public long StartingAmenitiesCapital { get; set; }
        public long StartingHousingCapital { get; set; }
        public long StartingAmenitiesOtherCities { get; set; }
        public long StartingHousingOtherCities { get; set; }
    
        public virtual Era Era { get; set; }
    }
}
