//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strategy_YieldPriorities
    {
        public string StrategyType { get; set; }
        public string YieldType { get; set; }
        public string PseudoYieldType { get; set; }
        public long PercentageDelta { get; set; }
    
        public virtual PseudoYield PseudoYield { get; set; }
        public virtual Strategy Strategy { get; set; }
        public virtual Yield Yield { get; set; }
    }
}
