//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreeData
    {
        public long DefnId { get; set; }
        public long NodeId { get; set; }
        public string TreeName { get; set; }
        public string Tag { get; set; }
        public string DefaultData { get; set; }
        public string ParentTag { get; set; }
        public long UniqueId { get; set; }
    
        public virtual BehaviorTree BehaviorTree { get; set; }
    }
}
