//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggeredBehaviorTree
    {
        public string TriggerType { get; set; }
        public string TreeName { get; set; }
        public string OperationName { get; set; }
        public string AIEvent { get; set; }
        public long Priority { get; set; }
    
        public virtual AiEvent AiEvent1 { get; set; }
        public virtual BehaviorTree BehaviorTree { get; set; }
    }
}
