//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnPhas
    {
        public long ID { get; set; }
        public string TurnPhaseType { get; set; }
        public long PhaseOrder { get; set; }
        public string TurnMode { get; set; }
        public string ActiveSegmentType { get; set; }
        public string InactiveSegmentType { get; set; }
    
        public virtual TurnSegment TurnSegment { get; set; }
        public virtual TurnSegment TurnSegment1 { get; set; }
    }
}
