//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type()
        {
            this.DynamicModifiers = new HashSet<DynamicModifier>();
            this.DynamicModifiers1 = new HashSet<DynamicModifier>();
            this.TypeProperties = new HashSet<TypeProperty>();
            this.Tags = new HashSet<Tag>();
        }
    
        public string Type1 { get; set; }
        public long Hash { get; set; }
        public string Kind { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Civic Civic { get; set; }
        public virtual Civilization Civilization { get; set; }
        public virtual Defeat Defeat { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicModifier> DynamicModifiers { get; set; }
        public virtual DynamicModifier DynamicModifier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicModifier> DynamicModifiers1 { get; set; }
        public virtual Government Government { get; set; }
        public virtual Improvement Improvement { get; set; }
        public virtual Kind Kind1 { get; set; }
        public virtual Leader Leader { get; set; }
        public virtual Policy Policy { get; set; }
        public virtual Project Project { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual Trait Trait { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeProperty> TypeProperties { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Victory Victory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
