//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_RebellionTags
    {
        public string Tag { get; set; }
        public long RebellionLevel { get; set; }
        public long NumCreated { get; set; }
        public string ForbiddenTag { get; set; }
    }
}
