//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Victory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Victory()
        {
            this.Strategies = new HashSet<Strategy>();
        }
    
        public string VictoryType { get; set; }
        public string Name { get; set; }
        public string Blurb { get; set; }
        public string RequirementSetId { get; set; }
        public bool EnabledByDefault { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Strategy> Strategies { get; set; }
        public virtual Type Type { get; set; }
    }
}
