//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivGen
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMD
    {
        public string WeaponType { get; set; }
        public string Name { get; set; }
        public long BlastRadius { get; set; }
        public long FalloutDuration { get; set; }
        public bool AffectPopulation { get; set; }
        public bool AffectImprovements { get; set; }
        public bool AffectBuildings { get; set; }
        public bool AffectUnits { get; set; }
        public bool AffectResources { get; set; }
        public bool AffectRoutes { get; set; }
        public long ICBMStrikeRange { get; set; }
        public long Maintenance { get; set; }
    }
}
